<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260224101554 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE workflow_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tenant_id VARCHAR(36) NOT NULL, subject_type VARCHAR(32) NOT NULL, subject_id VARCHAR(64) NOT NULL, transition VARCHAR(64) NOT NULL, from_place VARCHAR(32) DEFAULT NULL, to_place VARCHAR(32) NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actor VARCHAR(128) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_workflow_audit_tenant ON workflow_audit (tenant_id)');
        $this->addSql('CREATE INDEX idx_workflow_audit_subject ON workflow_audit (subject_type, subject_id)');
        $this->addSql('ALTER TABLE offers ALTER status DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE workflow_audit');
        $this->addSql('ALTER TABLE offers ALTER status SET DEFAULT \'draft\'');
    }
}
